version: 2.1
jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME
