# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build-image:
    jobs:
    machine: true
      - docker-login:
        - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - docker-build:
        - run: docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME .
      - docker-push:
        - run: docker push $DOCKER_USERNAME/$IMAGE_NAME
